import { Question, LearningPath, Achievement, LeaderboardEntry, PathId } from "./types";

export const QUESTIONS_BY_PATH: Record<PathId, Question[]> = {
  basics: [
    {
      id: 1,
      text: "What is Arc primarily built for?",
      options: ["Gaming and NFTs", "General-purpose computation", "Building and scaling financial applications with stablecoins", "Mining and staking"],
      correctAnswer: "Building and scaling financial applications with stablecoins",
    },
    {
      id: 2,
      text: "What type of blockchain is Arc?",
      options: ["A Layer-2 rollup on Ethereum", "A proof-of-work chain", "A purpose-built, EVM-compatible Layer-1 network", "A sidechain of Bitcoin"],
      correctAnswer: "A purpose-built, EVM-compatible Layer-1 network",
    },
    {
      id: 3,
      text: "Which token is used as Arc’s native gas token?",
      options: ["ETH", "ARC", "BTC", "USDC"],
      correctAnswer: "USDC",
    },
    {
      id: 4,
      text: "What is the target base fee per transaction on Arc?",
      options: ["$1.00", "$0.10", "~$0.01 (approximately one cent)", "Free — no fees"],
      correctAnswer: "~$0.01 (approximately one cent)",
    },
    {
      id: 5,
      text: "What is Arc’s consensus engine called?",
      options: ["Cosmos SDK", "Optimism", "Malachite", "Tendermint Classic"],
      correctAnswer: "Malachite",
    },
    {
      id: 6,
      text: "Which of the following is a key feature of Arc?",
      options: ["Random block finality", "High gas fees in ETH", "Deterministic sub-second finality", "Proof-of-work mining"],
      correctAnswer: "Deterministic sub-second finality",
    },
    {
      id: 7,
      text: "What stablecoins does Arc natively support?",
      options: ["DAI and USDT", "BUSD and FRAX", "USDC and EURC", "USDT and TUSD"],
      correctAnswer: "USDC and EURC",
    },
    {
      id: 8,
      text: "What does “EVM-compatible” mean for Arc developers?",
      options: ["You must rewrite contracts in a new language", "Arc has no smart contract support", "You can deploy existing Solidity contracts using standard tools like Hardhat and Foundry", "EVM is disabled on Arc"],
      correctAnswer: "You can deploy existing Solidity contracts using standard tools like Hardhat and Foundry",
    },
    {
      id: 9,
      text: "What Rust-based client powers Arc’s execution layer?",
      options: ["Geth", "Nethermind", "Reth", "Besu"],
      correctAnswer: "Reth",
    },
    {
      id: 10,
      text: "What EVM hard fork does Arc target?",
      options: ["Shanghai", "Cancun", "Prague", "Berlin"],
      correctAnswer: "Prague",
    },
    {
      id: 11,
      text: "What happens to the SELFDESTRUCT opcode on Arc?",
      options: ["It works exactly like Ethereum", "It is renamed to DESTROY", "It is not allowed during deployment to prevent burning native tokens", "It only works for validators"],
      correctAnswer: "It is not allowed during deployment to prevent burning native tokens",
    },
    {
      id: 12,
      text: "What are the three Arc-specific execution layer modules?",
      options: ["Mining, Staking, Voting", "Gas, Bridge, Oracle", "Fee Manager, Privacy Module, and Stablecoin Services", "Consensus, Relay, and Sync"],
      correctAnswer: "Fee Manager, Privacy Module, and Stablecoin Services",
    },
    {
      id: 13,
      text: "What does Arc’s Fee Manager do?",
      options: ["Converts ETH to USDC automatically", "Charges a flat fee per block", "Stabilizes fees by using USDC as the unit of account and smoothing fee changes", "Sets fees based on token price"],
      correctAnswer: "Stabilizes fees by using USDC as the unit of account and smoothing fee changes",
    },
    {
      id: 14,
      text: "What does PREV_RANDAO always return on Arc?",
      options: ["A random validator hash", "The previous block hash", "Always 0 — it is not used for randomness on Arc", "The current timestamp"],
      correctAnswer: "Always 0 — it is not used for randomness on Arc",
    },
    {
      id: 15,
      text: "How does Arc’s block timestamp differ from Ethereum?",
      options: ["Uses slot and epoch model like Ethereum", "Timestamps are set by miners", "Uses wall-clock time from the proposer with second-level granularity", "Blocks have no timestamps"],
      correctAnswer: "Uses wall-clock time from the proposer with second-level granularity",
    },
    {
      id: 16,
      text: "What is Arc primarily designed for compared to Ethereum?",
      options: ["General-purpose computation for all app types", "NFT marketplaces and gaming", "Real-world financial applications — payments, lending, FX, and capital markets", "Social media and content platforms"],
      correctAnswer: "Real-world financial applications — payments, lending, FX, and capital markets",
    },
  ],
  wallet: [
    {
      id: 1,
      text: "What is the Arc Testnet Chain ID?",
      options: ["1 (Ethereum Mainnet)", "137 (Polygon)", "5042002", "42161 (Arbitrum)"],
      correctAnswer: "5042002",
    },
    {
      id: 2,
      text: "What is the Arc Testnet RPC URL?",
      options: ["https://rpc.arc.network", "https://mainnet.arc.network", "https://rpc.testnet.arc.network", "https://arc.infura.io"],
      correctAnswer: "https://rpc.testnet.arc.network",
    },
    {
      id: 3,
      text: "What currency symbol should you enter when adding Arc Testnet to your wallet?",
      options: ["ETH", "ARC", "USDC", "GAS"],
      correctAnswer: "USDC",
    },
    {
      id: 4,
      text: "Where can developers get testnet USDC and EURC for Arc?",
      options: ["You must buy them on an exchange", "They are airdropped automatically", "From the Circle Faucet at faucet.circle.com", "From the Arc Discord bot"],
      correctAnswer: "From the Circle Faucet at faucet.circle.com",
    },
    {
      id: 5,
      text: "What is the Arc Testnet block explorer URL?",
      options: ["https://etherscan.io", "https://arcscan.io", "https://testnet.arcscan.app", "https://explorer.arc.network"],
      correctAnswer: "https://testnet.arcscan.app",
    },
    {
      id: 6,
      text: "If your wallet doesn’t support custom gas tokens, what happens on Arc?",
      options: ["Transactions are blocked entirely", "The wallet still works for signing and sending, but balances may display as “ETH”", "You must use a different wallet", "Gas is automatically converted to ETH"],
      correctAnswer: "The wallet still works for signing and sending, but balances may display as “ETH”",
    },
    {
      id: 7,
      text: "Which wallets are listed in Arc docs for manual testnet setup?",
      options: ["Trust Wallet and Phantom", "Ledger and Trezor", "MetaMask, Rabby, Coinbase Wallet, and Rainbow", "Exodus and Atomic Wallet"],
      correctAnswer: "MetaMask, Rabby, Coinbase Wallet, and Rainbow",
    },
    {
      id: 8,
      text: "What port does Arc’s JSON-RPC API (Execution Layer) use?",
      options: ["3000", "443", "8545", "8080"],
      correctAnswer: "8545",
    },
    {
      id: 9,
      text: "Which operating systems are supported for running an Arc node?",
      options: ["Windows and macOS only", "Any OS with Docker", "Linux — Ubuntu 22.04+ or Debian 12+", "All operating systems equally"],
      correctAnswer: "Linux — Ubuntu 22.04+ or Debian 12+",
    },
    {
      id: 10,
      text: "How much minimum memory (RAM) is required to run an Arc node?",
      options: ["8 GB", "16 GB", "32 GB", "64 GB+"],
      correctAnswer: "64 GB+",
    },
    {
      id: 11,
      text: "What storage type is recommended for running an Arc node?",
      options: ["HDD (mechanical hard drive)", "SATA SSD", "NVMe SSD (TLC recommended), 1 TB+", "USB external drive"],
      correctAnswer: "NVMe SSD (TLC recommended), 1 TB+",
    },
    {
      id: 12,
      text: "What minimum network bandwidth is needed to run an Arc node?",
      options: ["1 Mbps", "5 Mbps", "24 Mbps+ stable connection", "100 Mbps"],
      correctAnswer: "24 Mbps+ stable connection",
    },
    {
      id: 13,
      text: "What are the three required binaries to run an Arc node?",
      options: ["arc-wallet, arc-sync, arc-monitor", "arc-rpc, arc-validator, arc-storage", "arc-node-execution, arc-node-consensus, and arc-snapshots", "arc-client, arc-relay, arc-boot"],
      correctAnswer: "arc-node-execution, arc-node-consensus, and arc-snapshots",
    },
    {
      id: 14,
      text: "What is the arc-snapshots binary used for?",
      options: ["Taking screenshots of the block explorer", "Backing up your wallet", "Downloading blockchain snapshots for faster initial node sync", "Monitoring node health"],
      correctAnswer: "Downloading blockchain snapshots for faster initial node sync",
    },
  ],
  stablecoins: [
    {
      id: 1,
      text: "Why does Arc use USDC for gas fees instead of a native token?",
      options: ["Because ETH is too expensive", "To follow Ethereum’s standard", "So transaction costs stay predictable and don’t fluctuate with token price volatility", "Because USDC is faster to process"],
      correctAnswer: "So transaction costs stay predictable and don’t fluctuate with token price volatility",
    },
    {
      id: 2,
      text: "What fee smoothing mechanism does Arc use?",
      options: ["A fixed flat fee per block", "A Dutch auction model", "An exponentially weighted moving average (EWMA) of block utilization, similar to EIP-1559", "A random fee selector"],
      correctAnswer: "An exponentially weighted moving average (EWMA) of block utilization, similar to EIP-1559",
    },
    {
      id: 3,
      text: "How many decimals does USDC use for gas (native precision) on Arc?",
      options: ["6", "8", "18", "12"],
      correctAnswer: "18",
    },
    {
      id: 4,
      text: "How many decimals does USDC’s ERC-20 interface use for transfers and balance display on Arc?",
      options: ["18", "8", "12", "6"],
      correctAnswer: "6",
    },
    {
      id: 5,
      text: "Which euro-denominated stablecoin does Arc support?",
      options: ["EURT", "EURS", "EURC", "DAI-EUR"],
      correctAnswer: "EURC",
    },
    {
      id: 6,
      text: "What is a key benefit of dollar-denominated gas fees for enterprises?",
      options: ["Lower transaction throughput", "More complex accounting", "Simplified accounting, treasury management, and compliance reporting", "Fees that change every block"],
      correctAnswer: "Simplified accounting, treasury management, and compliance reporting",
    },
    {
      id: 7,
      text: "What stablecoins does App Kit’s Swap capability support?",
      options: ["Only USDC", "Only USDC and EURC", "Many stablecoins including USDC, EURC, USDT, USDe, and DAI", "Only native blockchain tokens"],
      correctAnswer: "Many stablecoins including USDC, EURC, USDT, USDe, and DAI",
    },
    {
      id: 8,
      text: "What is EURC on Arc used for?",
      options: ["Paying for gas fees in euros", "A speculative investment token", "Euro-denominated stablecoin transfers", "Converting ETH to EUR"],
      correctAnswer: "Euro-denominated stablecoin transfers",
    },
    {
      id: 9,
      text: "Why can’t tiny USDC amounts below 1×10⁻⁶ be transferred via the ERC-20 interface on Arc?",
      options: ["Arc blocks small transactions for security", "The network charges a minimum fee higher than that", "Because the ERC-20 interface uses 6 decimals, which cannot represent amounts that small", "Arc has a minimum transfer limit of $1"],
      correctAnswer: "Because the ERC-20 interface uses 6 decimals, which cannot represent amounts that small",
    },
    {
      id: 10,
      text: "When a protocol holds USDC as an ERC-20 on Arc, what else automatically happens?",
      options: ["The USDC is locked until withdrawn", "A separate native balance must be maintained manually", "Equivalent native balances are automatically held — no extra Solidity changes like payable are needed", "The protocol must register with Circle"],
      correctAnswer: "Equivalent native balances are automatically held — no extra Solidity changes like payable are needed",
    },
    {
      id: 11,
      text: "What is the relationship between Arc’s native USDC and its ERC-20 USDC interface?",
      options: ["They are completely separate tokens", "Native USDC uses 6 decimals, ERC-20 uses 18", "Native USDC uses 18 decimals for gas accounting; the ERC-20 interface uses 6 decimals to match standard USDC on other chains", "There is no ERC-20 interface for USDC on Arc"],
      correctAnswer: "Native USDC uses 18 decimals for gas accounting; the ERC-20 interface uses 6 decimals to match standard USDC on other chains",
    },
    {
      id: 12,
      text: "Which real-world use case does Arc’s stablecoin FX feature enable?",
      options: ["Mining stablecoins", "Locking stablecoins in yield vaults", "Real-time onchain cross-currency swaps between stablecoins with transparent pricing and instant settlement", "Issuing new stablecoins"],
      correctAnswer: "Real-time onchain cross-currency swaps between stablecoins with transparent pricing and instant settlement",
    },
  ],
  testnet: [
    {
      id: 1,
      text: "What is the minimum base fee on Arc Testnet?",
      options: ["1 Gwei", "5 Gwei", "100 Gwei", "20 Gwei"],
      correctAnswer: "20 Gwei",
    },
    {
      id: 2,
      text: "What happens if you submit a transaction with a maxFeePerGas below 20 Gwei on Arc Testnet?",
      options: ["It gets processed with a discount", "It is automatically bumped to the minimum", "It may remain pending or fail to execute", "Nothing — fees are optional"],
      correctAnswer: "It may remain pending or fail to execute",
    },
    {
      id: 3,
      text: "Where can you view real-time gas metrics on Arc Testnet?",
      options: ["docs.arc.network/gas", "etherscan.io/gas", "testnet.arcscan.app/gas-tracker", "arc.network/dashboard"],
      correctAnswer: "testnet.arcscan.app/gas-tracker",
    },
    {
      id: 4,
      text: "What consensus model does Arc use for its validator set?",
      options: ["Delegated Proof-of-Stake (DPoS)", "Proof-of-Work (PoW)", "Proof-of-Authority (PoA) with permissioned, regulated institutional validators", "Proof-of-History (PoH)"],
      correctAnswer: "Proof-of-Authority (PoA) with permissioned, regulated institutional validators",
    },
    {
      id: 5,
      text: "How many TPS can Arc achieve with 20 globally distributed validators?",
      options: ["100 TPS", "500 TPS", "3,000+ TPS", "10 TPS"],
      correctAnswer: "3,000+ TPS",
    },
    {
      id: 6,
      text: "What finality time does Arc achieve under benchmark conditions?",
      options: ["12–15 minutes (like Ethereum)", "~2 seconds", "Under 350ms", "~1 minute"],
      correctAnswer: "Under 350ms",
    },
    {
      id: 7,
      text: "What privacy feature does Arc have on its roadmap (but not yet live)?",
      options: ["Full public transparency only", "Zero-knowledge proofs for all transactions by default", "Opt-in confidential transfers where transaction amounts are encrypted", "Mandatory private transactions"],
      correctAnswer: "Opt-in confidential transfers where transaction amounts are encrypted",
    },
    {
      id: 8,
      text: "What are “view keys” in Arc’s privacy model?",
      options: ["Keys that let you view the blockchain explorer", "Master admin keys for validators", "Keys that grant controlled read access to confidential transaction data for auditors or regulators", "Wallet recovery keys"],
      correctAnswer: "Keys that grant controlled read access to confidential transaction data for auditors or regulators",
    },
    {
      id: 9,
      text: "What is the current Arc Testnet version?",
      options: ["v1.0.0", "v0.4.2", "v0.6.0", "v2.1.0"],
      correctAnswer: "v0.6.0",
    },
    {
      id: 10,
      text: "Which node providers offer RPC relay endpoints for Arc Testnet?",
      options: ["Infura and Alchemy", "Moralis and QuickNode", "DRPC, QuickNode, and Blockdaemon", "Chainstack and Ankr"],
      correctAnswer: "DRPC, QuickNode, and Blockdaemon",
    },
    {
      id: 11,
      text: "What happens to Arc consensus if fewer than one-third of validators go offline?",
      options: ["The network stops entirely", "Finality slows to minutes", "The network continues operating — Tendermint BFT only fails if more than one-third of validators are Byzantine", "A new validator set is elected immediately"],
      correctAnswer: "The network continues operating — Tendermint BFT only fails if more than one-third of validators are Byzantine",
    },
    {
      id: 12,
      text: "Which Tendermint phase comes immediately after Pre-vote?",
      options: ["Propose", "Commit", "Pre-commit", "Validate"],
      correctAnswer: "Pre-commit",
    },
    {
      id: 13,
      text: "What performance can Arc achieve with only 4 validators?",
      options: ["3,000 TPS", "5,000 TPS", "10,000+ TPS", "500 TPS"],
      correctAnswer: "10,000+ TPS",
    },
    {
      id: 14,
      text: "What is the purpose of the arc-node-consensus binary?",
      options: ["It executes smart contracts", "It stores blockchain snapshots", "It runs the Malachite-based consensus layer — fetching and verifying blocks", "It provides the JSON-RPC API"],
      correctAnswer: "It runs the Malachite-based consensus layer — fetching and verifying blocks",
    },
    {
      id: 15,
      text: "How do Arc validators differ from Ethereum validators?",
      options: ["Arc uses anonymous stakers like Ethereum PoS", "Arc validators are chosen by token holders", "Arc validators are permissioned, regulated institutions with compliance obligations and uptime SLAs", "Arc has no validators — it uses miners"],
      correctAnswer: "Arc validators are permissioned, regulated institutions with compliance obligations and uptime SLAs",
    },
    {
      id: 16,
      text: "What is the “optimistic responsiveness” property of Arc’s Tendermint implementation?",
      options: ["The network optimistically assumes all transactions are valid", "Blocks are produced on a fixed 12-second schedule", "Block production and confirmation proceed as fast as the network allows with no artificial delays or extra timeouts", "Validators optimistically skip the pre-vote phase"],
      correctAnswer: "Block production and confirmation proceed as fast as the network allows with no artificial delays or extra timeouts",
    },
  ],
  building: [
    {
      id: 1,
      text: "What is Arc App Kit?",
      options: ["A mobile wallet app", "A block explorer tool", "An SDK for building crosschain payment workflows including send, bridge, swap, and unified balance", "A validator management tool"],
      correctAnswer: "An SDK for building crosschain payment workflows including send, bridge, swap, and unified balance",
    },
    {
      id: 2,
      text: "What does App Kit’s Unified Balance feature do?",
      options: ["Locks your USDC to a single chain", "Converts USDC to ETH automatically", "Combines USDC from multiple blockchains into a single, instantly spendable balance", "Bridges tokens one chain at a time manually"],
      correctAnswer: "Combines USDC from multiple blockchains into a single, instantly spendable balance",
    },
    {
      id: 3,
      text: "Which ERC standard does Arc use for registering AI agents with onchain identity?",
      options: ["ERC-20", "ERC-721", "ERC-1155", "ERC-8004"],
      correctAnswer: "ERC-8004",
    },
    {
      id: 4,
      text: "What is the Arc MCP Server used for?",
      options: ["Running validator nodes", "Staking USDC", "Enabling AI agents to interact with Arc using the Model Context Protocol", "Managing wallet recovery"],
      correctAnswer: "Enabling AI agents to interact with Arc using the Model Context Protocol",
    },
    {
      id: 5,
      text: "Which of the following are use cases Arc is specifically built for?",
      options: ["Gaming and metaverse", "NFT minting and art", "Peer-to-peer payments, eCommerce checkout, stablecoin FX, and agentic economy", "Social media and content creation"],
      correctAnswer: "Peer-to-peer payments, eCommerce checkout, stablecoin FX, and agentic economy",
    },
    {
      id: 6,
      text: "What does “Circle Gas Station” do for developers on Arc Testnet?",
      options: ["Charges extra fees for fast transactions", "Requires manual fee submission", "Automatically sponsors transaction fees when using Circle dev-controlled wallets", "Converts ETH to USDC for gas"],
      correctAnswer: "Automatically sponsors transaction fees when using Circle dev-controlled wallets",
    },
    {
      id: 7,
      text: "What pre-audited contract templates can be deployed on Arc via Circle Contracts?",
      options: ["Only ERC-20 tokens", "Only NFTs", "ERC-20, ERC-721, ERC-1155, and Airdrop templates", "Solidity 0.4.x legacy contracts only"],
      correctAnswer: "ERC-20, ERC-721, ERC-1155, and Airdrop templates",
    },
    {
      id: 8,
      text: "What does App Kit’s Bridge capability abstract away from developers?",
      options: ["The need to write Solidity contracts", "Wallet connection logic", "The low-level CCTP burn, attestation, and mint steps required for crosschain USDC transfers", "Gas fee estimation"],
      correctAnswer: "The low-level CCTP burn, attestation, and mint steps required for crosschain USDC transfers",
    },
    {
      id: 9,
      text: "What underlying protocol does App Kit’s Bridge use to move USDC across chains?",
      options: ["LayerZero", "Wormhole", "CCTP (Cross-Chain Transfer Protocol) by Circle", "Axelar"],
      correctAnswer: "CCTP (Cross-Chain Transfer Protocol) by Circle",
    },
    {
      id: 10,
      text: "What does App Kit’s Swap capability do?",
      options: ["Bridges tokens between different blockchains", "Converts fiat to crypto", "Swaps two tokens on the same blockchain in a few lines of code", "Swaps validator slots"],
      correctAnswer: "Swaps two tokens on the same blockchain in a few lines of code",
    },
    {
      id: 11,
      text: "Which of these is a production-ready sample app available in Arc’s docs?",
      options: ["Arc NFT Marketplace", "Arc Gaming Hub", "Arc Multichain Wallet — a unified USDC balance and crosschain transfer app built with Circle Gateway, Next.js, and Supabase", "Arc Social Network"],
      correctAnswer: "Arc Multichain Wallet — a unified USDC balance and crosschain transfer app built with Circle Gateway, Next.js, and Supabase",
    },
    {
      id: 12,
      text: "What standard does Arc use for onchain AI agent job settlement?",
      options: ["ERC-20", "ERC-721", "ERC-8004", "ERC-8183"],
      correctAnswer: "ERC-8183",
    },
    {
      id: 13,
      text: "What does the ERC-8004 standard on Arc provide for AI agents?",
      options: ["A token standard for agent rewards", "A smart contract template for DEXes", "Onchain identity and reputation registry for AI agents", "A job posting and settlement protocol"],
      correctAnswer: "Onchain identity and reputation registry for AI agents",
    },
    {
      id: 14,
      text: "What is the Arc escrow sample app designed to demonstrate?",
      options: ["NFT minting on Arc", "Token swapping between wallets", "AI-powered work validation and USDC settlement to automate escrow flows", "Running a validator node"],
      correctAnswer: "AI-powered work validation and USDC settlement to automate escrow flows",
    },
    {
      id: 15,
      text: "What three technologies does the Arc commerce sample app use?",
      options: ["Hardhat, Remix, and IPFS", "Foundry, Viem, and PostgreSQL", "Circle Developer Controlled Wallets, Next.js, and Supabase", "Truffle, Web3.js, and Firebase"],
      correctAnswer: "Circle Developer Controlled Wallets, Next.js, and Supabase",
    },
  ],
  deploying: [
    {
      id: 1,
      text: "Which development tools does Arc’s EVM compatibility support out of the box?",
      options: ["Only Truffle", "Only Remix IDE", "Hardhat, Foundry, and Viem — standard Ethereum tooling works without modification", "Custom Arc-only SDKs"],
      correctAnswer: "Hardhat, Foundry, and Viem — standard Ethereum tooling works without modification",
    },
    {
      id: 2,
      text: "What is the recommended Node.js version for Arc development tutorials?",
      options: ["Node.js v14+", "Node.js v16+", "Node.js v22+", "Node.js v12+"],
      correctAnswer: "Node.js v22+",
    },
    {
      id: 3,
      text: "What post-quantum signature scheme does Arc plan to support at mainnet launch?",
      options: ["RSA-4096", "Ed25519", "SLH-DSA-SHA2-128s", "ECDSA-256"],
      correctAnswer: "SLH-DSA-SHA2-128s",
    },
    {
      id: 4,
      text: "What are the two main risks post-quantum security addresses on Arc?",
      options: ["Slow finality and high fees", "Smart contract bugs and rug pulls", "Signature forgery and harvest-now, decrypt-later attacks on encrypted data", "Network downtime and validator fraud"],
      correctAnswer: "Signature forgery and harvest-now, decrypt-later attacks on encrypted data",
    },
    {
      id: 5,
      text: "In the Tendermint consensus process, how many validator phases happen before a block is committed?",
      options: ["One (single vote)", "Three (propose, vote, finalize)", "Four (Propose, Pre-vote, Pre-commit, Commit)", "Two (propose, confirm)"],
      correctAnswer: "Four (Propose, Pre-vote, Pre-commit, Commit)",
    },
    {
      id: 6,
      text: "What does App Kit’s bridge fee estimation allow developers to do?",
      options: ["Automatically waive all fees", "Charge users in ETH only", "Estimate crosschain bridge costs before submitting a transaction so users see transparent pricing", "Skip the bridge and transfer directly"],
      correctAnswer: "Estimate crosschain bridge costs before submitting a transaction so users see transparent pricing",
    },
    {
      id: 7,
      text: "What is the purpose of Arc’s “forwarding service” in App Kit?",
      options: ["It forwards emails about transactions", "It relays blocks to validators", "It enables transactions to be submitted on behalf of users, useful for gasless or delegated flows", "It forwards stablecoins to a savings wallet"],
      correctAnswer: "It enables transactions to be submitted on behalf of users, useful for gasless or delegated flows",
    },
    {
      id: 8,
      text: "What is ERC-8183 on Arc?",
      options: ["A stablecoin standard", "A governance proposal format", "A standard for creating onchain jobs that AI agents can pick up and execute for payment", "An NFT metadata extension"],
      correctAnswer: "A standard for creating onchain jobs that AI agents can pick up and execute for payment",
    },
    {
      id: 9,
      text: "What does the App Kit forwarding service enable?",
      options: ["Automatic token price conversion", "Faster block finality", "Transactions to be submitted on behalf of users — useful for gasless or delegated payment flows", "Forwarding validator rewards to wallets"],
      correctAnswer: "Transactions to be submitted on behalf of users — useful for gasless or delegated payment flows",
    },
    {
      id: 10,
      text: "What is slippage tolerance in the context of App Kit Swap?",
      options: ["The maximum fee a user will pay", "The time limit for a swap to complete", "The maximum acceptable difference between the expected and actual swap price before the transaction is rejected", "The minimum liquidity required in a pool"],
      correctAnswer: "The maximum acceptable difference between the expected and actual swap price before the transaction is rejected",
    },
    {
      id: 11,
      text: "What is a “stop limit” in App Kit Swap?",
      options: ["A limit on how many swaps per day", "A maximum gas fee setting", "A condition that triggers a swap only when the token price reaches a specified level", "A developer-set cap on swap volume"],
      correctAnswer: "A condition that triggers a swap only when the token price reaches a specified level",
    },
    {
      id: 12,
      text: "What does the Unified Balance delegate feature allow?",
      options: ["A validator to manage user funds", "Circle to approve transactions automatically", "A third party (delegate) to spend from a user’s Unified Balance on their behalf without holding the private key", "Automatic daily rebalancing across chains"],
      correctAnswer: "A third party (delegate) to spend from a user’s Unified Balance on their behalf without holding the private key",
    },
    {
      id: 13,
      text: "How can funds be removed from a Unified Balance trustlessly?",
      options: ["Only by contacting Circle support", "By waiting 7 days for an automatic release", "Through a trustless withdrawal mechanism that lets users remove funds directly without relying on any intermediary", "By swapping to a different token first"],
      correctAnswer: "Through a trustless withdrawal mechanism that lets users remove funds directly without relying on any intermediary",
    },
    {
      id: 14,
      text: "What does “collect bridge fee” mean in App Kit?",
      options: ["Circle charges a fee to your credit card", "The validator takes a cut of every transfer", "Developers can add their own custom fee on top of the bridge transaction and collect it directly", "Arc automatically collects fees from users"],
      correctAnswer: "Developers can add their own custom fee on top of the bridge transaction and collect it directly",
    },
    {
      id: 15,
      text: "What is the purpose of estimating bridge costs before submitting?",
      options: ["To check if the user has enough ETH", "To predict block finality time", "To show users transparent, upfront pricing so they know the exact cost before confirming a crosschain transfer", "To reserve a slot in the next block"],
      correctAnswer: "To show users transparent, upfront pricing so they know the exact cost before confirming a crosschain transfer",
    },
    {
      id: 16,
      text: "What does “configure transfer speed” in App Kit Bridge allow developers to do?",
      options: ["Set a specific block for the transfer to execute", "Pause a transfer mid-flight", "Choose between faster or slower transfer modes which affect the cost and confirmation time of the bridge", "Change the RPC endpoint mid-transfer"],
      correctAnswer: "Choose between faster or slower transfer modes which affect the cost and confirmation time of the bridge",
    },
  ],
};

export const LEARNING_PATHS: LearningPath[] = [
  { id: "basics", title: "Arc Basics", difficulty: "Beginner", time: "15 min", xp: 250, icon: "BookOpen" },
  { id: "wallet", title: "Wallet Setup", difficulty: "Beginner", time: "10 min", xp: 200, icon: "Wallet" },
  { id: "stablecoins", title: "Stablecoins 101", difficulty: "Beginner", time: "20 min", xp: 300, icon: "Coins" },
  { id: "testnet", title: "Arc Testnet", difficulty: "Intermediate", time: "30 min", xp: 500, icon: "FlaskConical" },
  { id: "building", title: "Building on Arc", difficulty: "Intermediate", time: "45 min", xp: 750, icon: "Code2" },
  { id: "deploying", title: "Deploying Apps", difficulty: "Advanced", time: "60 min", xp: 1000, icon: "Rocket" },
];

export const ACHIEVEMENTS: Achievement[] = [
  { id: "wallet-connected", title: "Wallet Connected", icon: "Link", description: "Successfully linked your first wallet." },
  { id: "testnet-explorer", title: "Testnet Explorer", icon: "Globe", description: "Explored the Arc testnet features." },
  { id: "stablecoin-learner", title: "Stablecoin Learner", icon: "CircleDollarSign", description: "Completed the Stablecoins 101 path." },
  { id: "first-builder", title: "First Builder", icon: "Hammer", description: "Built your first prototype on Arc." },
  { id: "deployment-ready", title: "Deployment Ready", icon: "CheckCircle", description: "All systems go for mainnet." },
];

export const LEADERBOARD: LeaderboardEntry[] = [
  { id: 1, username: "BlockBuilder", xp: 2450 },
  { id: 2, username: "StableDev", xp: 1980 },
  { id: 3, username: "ChainWizard", xp: 1650 },
  { id: 4, username: "NeoArc", xp: 1420 },
  { id: 5, username: "GlowRunner", xp: 1200 },
];
